### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mukhyala** [lianos/multiGSEA#17]
Hi Steve,

We use the master branch of multiGSEA (v0.11.1) which does not pass tests on R 3.5.1 using Bioc 3.8. Would you be able to fix these tests? Any advice would be great.

`
> library(multiGSEA)
Loading required package: edgeR
Loading required package: limma
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Warning messages:
1: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘multiGSEA’ 
2: replacing previous import ‘data.table::melt’ by ‘reshape2::melt’ when loading ‘multiGSEA’ 
3: replacing previous import ‘data.table::dcast’ by ‘reshape2::dcast’ when loading ‘multiGSEA’ 
4: replacing previous import ‘plotly::filter’ by ‘stats::filter’ when loading ‘multiGSEA’ 
> packageDescription('multiGSEA')
Package: multiGSEA
Type: Package
Title: A unified interface to a plethora of gene set enrichment
        analysis methods
Version: 0.11.1
Authors@R: c( person("Steve", "Lianoglou", , "slianoglou@gmail.com",
        c("aut", "cre")), person("Genentech", role = c("cph", "fnd")),
        person("Denali Therapeutics", role = c("fnd")) )
Description: Provides a unified interface to orchestrate a plethora of
        GSEA methods over a contrast of interest as well as single
        sample gene set scoring methods. This package also provides
        robust interactive tools to explore GSEA results.
Depends: edgeR (>= 3.18.1)
Imports: BiocGenerics, BiocParallel, Biobase (>= 2.24.0), circlize,
        ComplexHeatmap, ggplot2 (>= 2.2.0), GSEABase, GSVA, data.table
        (>= 1.10.4), magrittr, Matrix, matrixStats, methods, plotly (>=
        4.7.0), reshape2, viridis, limma
Suggests: AnnotationDbi, BiocStyle, DESeq2, dplyr, dtplyr,
        GeneSetDb.MSigDB.Hsapiens.v61, GeneSetDb.MSigDB.Mmusculus.v61,
        fgsea, GO.db, goseq, KernSmooth, knitr, org.Hs.eg.db,
        org.Mm.eg.db, PANTHER.db (>= 1.0.3), reactome.db,
        SummarizedExperiment, statmod, testthat, webshot
VignetteBuilder: knitr
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Collate: 'AllClasses.R' 'AllGenerics.R' 'GeneSetDb-class.R' .....
RoxygenNote: 6.0.1.9000
biocViews: Pathways, GeneSetEnrichment, DifferentialExpression, GO,
        RNASeq
NeedsCompilation: no
Packaged: 2019-03-28 16:47:55 UTC; mukhyala
Author: Steve Lianoglou [aut, cre], Genentech [cph, fnd], Denali
        Therapeutics [fnd]
Maintainer: Steve Lianoglou <slianoglou@gmail.com>
Built: R 3.6.0; ; 2019-03-28 20:41:18 UTC; unix

-- File: /***/Rlib/3.5.1-Bioc-3.8-test/multiGSEA/Meta/package.rds 
> library(devtools)
> test('.')
Loading multiGSEA
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘multiGSEA’

Attaching package: ‘testthat’

The following objects are masked from ‘package:devtools’:

    setup, test_file

Attaching package: ‘magrittr’

The following objects are masked from ‘package:testthat’:

    equals, is_less_than, not

data.table 1.12.0  Latest news: r-datatable.com

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following object is masked from ‘package:testthat’:

    matches

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Testing multiGSEA
✔ | OK F W S | Context
✔ |  0     1 | Testing GSEA results in adversarial situations
────────────────────────────────────────────────────────────────────────────────
test-adversarial-gsea.R:4: skip: Gene Sets with logFCs in oppossite extremes
Empty test
────────────────────────────────────────────────────────────────────────────────
✔ | 15       | calculateIndividualLogFC [138.9 s]
✔ |  9       | camera [141.1 s]
✔ |  2       | Using DGEList's as input [46.7 s]
✔ |  9       | fgsea [81.1 s]
✔ |  6       | fry [65.1 s]
✔ | 1586     1 | GeneSetDb [1013.7 s]
────────────────────────────────────────────────────────────────────────────────
test-GeneSetDb.R:470: skip: GeneSetDb indexing `[` works
Empty test
────────────────────────────────────────────────────────────────────────────────
✔ |  1       | geneSetsStats [106.4 s]
✔ |  6       | geneSetSummaryByGenes [107.5 s]
✖ |  0 1     | geneSetTest [64.0 s]
────────────────────────────────────────────────────────────────────────────────
test-geneSetTest.R:21: error: geneSetTest matches re-implememtation
Unexpected geneset ordering in `geneSetTest` result
1: result(mg, "geneSetTest") at /***/multiGSEA/tests/testthat/test-geneSetTest.R:21
2: (function() {
       fnname <- sub("\\..*$", "", name)
       fnname <- paste0("mgres.", fnname)
       fnfetch <- getFunction(fnname)
       r <- fnfetch(x@results[[name]], geneSetDb(x))
       kosher <- all.equal(out[, key(out), with = FALSE], r[, key(out), with = FALSE])[1L]
       if (!isTRUE(kosher)) {
           stop("Unexpected geneset ordering in `", name, "` result")
       }
       if (!all(c("pval", "padj") %in% colnames(r))) {
           stop(fnname, " does not provide pval and/or padj column")
       }
       if (stats.only) {
           res.cols <- names(r)[grepl("^(pval\\.?|padj\\.?)", names(r))]
       }
       else {
           res.cols <- setdiff(names(r), names(out))
       }
       r <- r[, res.cols, with = FALSE]
       r
   })() at /***/multiGSEA/R/MultiGSEAResult-methods.R:299
3: stop("Unexpected geneset ordering in `", name, "` result") at /***/projects/multiGSEA/R/MultiGSEAResult-methods.R:316
────────────────────────────────────────────────────────────────────────────────
✔ | 10       | goseq [163.1 s]
✖ |  0 1     | Hyper Geometric Test [11.8 s]
────────────────────────────────────────────────────────────────────────────────
test-hyperGeometricTest.R:30: error: hyperGeometricTest performs like do.hyperGeometricTest performs
Unexpected geneset ordering in `hyperGeometricTest` result
1: results(mg) at /***/multiGSEA/tests/testthat/test-hyperGeometricTest.R:30
2: result(x, name, stats.only, rank.by, add.suffix, as.dt = TRUE) at /***/multiGSEA/R/MultiGSEAResult-methods.R:393
3: (function() {
       fnname <- sub("\\..*$", "", name)
       fnname <- paste0("mgres.", fnname)
       fnfetch <- getFunction(fnname)
       r <- fnfetch(x@results[[name]], geneSetDb(x))
       kosher <- all.equal(out[, key(out), with = FALSE], r[, key(out), with = FALSE])[1L]
       if (!isTRUE(kosher)) {
           stop("Unexpected geneset ordering in `", name, "` result")
       }
       if (!all(c("pval", "padj") %in% colnames(r))) {
           stop(fnname, " does not provide pval and/or padj column")
       }
       if (stats.only) {
           res.cols <- names(r)[grepl("^(pval\\.?|padj\\.?)", names(r))]
       }
       else {
           res.cols <- setdiff(names(r), names(out))
       }
       r <- r[, res.cols, with = FALSE]
       r
   })() at /***/multiGSEA/R/MultiGSEAResult-methods.R:299
4: stop("Unexpected geneset ordering in `", name, "` result") at /***/multiGSEA/R/MultiGSEAResult-methods.R:316
────────────────────────────────────────────────────────────────────────────────
✔ |  0       | Interactive Plotting
✔ |  5       | Pass-through logFC GSEA method [39.1 s]
✔ |  3       | multiGSEA [30.1 s]
✔ |  4     1 | MultiGSEAResult [14.5 s]
────────────────────────────────────────────────────────────────────────────────
test-MultiGSEAResult.R:3: skip: subset.MultiGSEAResult works
Empty test
────────────────────────────────────────────────────────────────────────────────
✔ |  0       | PANTHER.db
✔ |  4       | roast [13.0 s]
✔ |  9       | romer [41.1 s]
✔ | 10       | Single Sample Gene Set Scoring [115.1 s]
✖ |  6 2     | Errors submitted by users [23.3 s]
────────────────────────────────────────────────────────────────────────────────
test-users.R:19: failure: multiGSEA fails with a 1-geneset GeneSetDb
`printed` inherits from `NULL` not `character`.

test-users.R:23: error: multiGSEA fails with a 1-geneset GeneSetDb
Unexpected geneset ordering in `geneSetTest` result
1: result(mg, method) at /***/projects/multiGSEA/tests/testthat/test-users.R:23
2: (function() {
       fnname <- sub("\\..*$", "", name)
       fnname <- paste0("mgres.", fnname)
       fnfetch <- getFunction(fnname)
       r <- fnfetch(x@results[[name]], geneSetDb(x))
       kosher <- all.equal(out[, key(out), with = FALSE], r[, key(out), with = FALSE])[1L]
       if (!isTRUE(kosher)) {
           stop("Unexpected geneset ordering in `", name, "` result")
       }
       if (!all(c("pval", "padj") %in% colnames(r))) {
           stop(fnname, " does not provide pval and/or padj column")
       }
       if (stats.only) {
           res.cols <- names(r)[grepl("^(pval\\.?|padj\\.?)", names(r))]
       }
       else {
           res.cols <- setdiff(names(r), names(out))
       }
       r <- r[, res.cols, with = FALSE]
       r
   })() at /***/multiGSEA/R/MultiGSEAResult-methods.R:299
3: stop("Unexpected geneset ordering in `", name, "` result") at /***/multiGSEA/R/MultiGSEAResult-methods.R:316
────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 2216.8 s

OK:       1685
Failed:   4
Warnings: 0
Skipped:  3
Warning messages:
1: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘multiGSEA’ 
2: replacing previous import ‘data.table::melt’ by ‘reshape2::melt’ when loading ‘multiGSEA’ 
3: replacing previous import ‘data.table::dcast’ by ‘reshape2::dcast’ when loading ‘multiGSEA’ 
4: replacing previous import ‘plotly::filter’ by ‘stats::filter’ when loading ‘multiGSEA’ 
`

Thanks,
-Kiran

**Comment by lianos** [comment]
Will do, give me a couple of days.

**Comment by mukhyala** [comment]
Thanks!

**Comment by lianos** [comment]
Commits 7826f0b0c18d3f7b1c8e80dad2a30c233d8665c7 (with version bump in 92745f4f046b09aaf34dd213ee9350e39f8bb173) include a fair bit of mojo plus fixes to the failing tests.

I've got 1700 (even(!)) passing tests on my side with 3 skipped ... to be implemented at another time.

@mukhyala thanks for poking me to fix and glad to see that my ghost still haunts some of the halls at GNE ;-) Hope all's well!

**Comment by mukhyala** [comment]
Thanks for a quick fix Steve! 
Haunting ghosts would be an understatement! I've even heard of someone missing out on watching 168 movies on airplanes due to exploring data with FacileExplorer using the local installation. 
Will cost you a beer@F&L to learn more though ...
