### ISSUE TITLE
missing testdata file

### ISSUE THREAD

**Issue by mukhyala** [lianos/multiGSEA#19]
testing-helpers.R refers to TCGA-BRCA-some.DGEList.rds which is missing in the testdata directory. This is resulting in a lot of test failures. R CMD build is also failing probably for the same reason.

**Comment by lianos** [comment]
Fixed by 6c083b133cff19796d9fa2fd94154ffd2aa8f746

Sorry for neglecting to add the *.rds binary file to the repo, @mukhyala
