### ISSUE TITLE
R CMD check failures

### ISSUE THREAD

**Issue by mukhyala** [lianos/multiGSEA#21]
Hi Steve,

Any chance you can check if R CMD check passes on v 0.12.1? I am seeing 
missing imports:
1. geom_point and geom_hex in volcano_plot.R
2. theme_bw in plots-interactive.R

The vignette also has some issues building after fixing the imports:
....
* checking PDF version of manual without hyperrefs or index ... ERROR
* DONE
Status: 1 ERROR, 7 WARNINGs, 4 NOTEs

**Comment by mukhyala** [comment]
Thanks comrade!

**Comment by jonocarroll** [comment]
FYI, `geom_hex()`, even when plotly-fying, needs various functions from `{hexbin}` and this is only in `Suggests` for `{ggplot2}`. You may want to add this to `Imports` for `{multiGSEA}`.

**Comment by lianos** [comment]
Thanks for the heads up, Jonathan!

FYI, I've renamed this package to sparrow to accommodate for the multiGSEA package that was submitted to bioconductor last year. The fix you suggest was applied there: lianos/sparrow@532083b.

I plan on submitting sparrow to Bioc for review this dev cycle, so if you folks are still using this package I suggest to migrate to sparrow. I am happy to help if you have any questions with that.
